# Generated by Django 3.0.8 on 2020-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019)),
                ('present_price', models.FloatField()),
                ('kms_driven', models.IntegerField()),
                ('owner', models.CharField(choices=[('0', 'First Owner'), ('1', 'Second Owner')], default='First Owner', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'Cng')], default='Petrol', max_length=20)),
                ('seller_type', models.CharField(choices=[('individual', 'Individual'), ('dealer', 'Dealer')], default='Individual', max_length=40)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='Automatic', max_length=40)),
            ],
        ),
    ]
